### ISSUE TITLE
'genbtskey.py' fails when calling 'keyToBTSPubKey' with a specific private WIF key as input

### ISSUE THREAD

**Issue by fivepiece** [xeroc/pytshares#2]
I was feeding `genbtskey.py` some private keys I generated using my own code and I have noticed that the private key:

`5Jb4UGFBi2pAdWAAuew96quPGuwXUHtHqJNjv3zS1udBkosG5np`

Given as input will cause the software to crash:
```
$ python genbtskey.py 5Jb4UGFBi2pAdWAAuew96quPGuwXUHtHqJNjv3zS1udBkosG5np
Secret Exponent         : 65aa2c74bab107e79709ce90bbf89617870cbe5603a3b379eca9964b2fc3b609 
Private Key             : 5Jb4UGFBi2pAdWAAuew96quPGuwXUHtHqJNjv3zS1udBkosG5np 
BTC Address             : 1CkpBKDDWFBXFsbWXB7veHZuDYcvitJobV 
--------------------------------------------------------------------------------
BTC Pubkey (compressed) : 026004073b68533c9c1754ff4b20c2b348d718bdf3dc0af4d10dbccc437c5c8de 
BTC Address             : 1CkpBKDDWFBXFsbWXB7veHZuDYcvitJobV 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "genbtskey.py", line 196, in <module>
    print "BTS PubKey              : %s " % keyToBTSPubKey(private_key)
  File "genbtskey.py", line 103, in keyToBTSPubKey
    btspubkey  = compressedpubkey(s).decode('hex')
  File "/usr/lib/python2.7/encodings/hex_codec.py", line 42, in hex_decode
    output = binascii.a2b_hex(input)
TypeError: Odd-length string
```

Running the private key against my own software (a clone of `genbtskey.py` written in bash) gives this output with the same key:

```
Secret Exponent           : 65aa2c74bab107e79709ce90bbf89617870cbe5603a3b379eca9964b2fc3b609
Private Key (WIF)         : 5Jb4UGFBi2pAdWAAuew96quPGuwXUHtHqJNjv3zS1udBkosG5np
Public Key (Uncompressed) : 0406004073b68533c9c1754ff4b20c2b348d718bdf3dc0af4d10dbccc437c5c8de00759e933f62759efb9b8ce92dd6c9ec9ec8372f06d6f83047c679cb60ad2d86
BTC Address (Uncomressed) : 1CkpBKDDWFBXFsbWXB7veHZuDYcvitJobV
Public key (Compressed)   : 0206004073b68533c9c1754ff4b20c2b348d718bdf3dc0af4d10dbccc437c5c8de
BTC Address (Compressed)  : 1CPut7hkXgdEphXpErh8EAXBgfNhJsS6Bf
BTS Public Key            : BTS4w8e7bXzncYPMGw7U5Z7yxTWJqkE3WNBVhxNDtiMzc6oR23nh4
BTS Address               : BTS3qf5whTVCLxS5nK6vC9kaZsN3Xos8vVrt
PTS Address               : PjKh2CPtHnaJcyLfcMLyPBmEvuoX1rNHCj
```

I have also checked the WIF key at `bitaddress.org` and it returns the same keys and addresses as my own output.

**Comment by fivepiece** [comment]
Update : 
My software might be broken.
Closing this until I run more tests.
Sorry.

**Comment by fivepiece** [comment]
Edited correct output.
Reopened

**Comment by xeroc** [comment]
I noticed this too ... Might be related to b58 padding or the way compressedpubkey works. Thanks for reporting

**Comment by xeroc** [comment]
fixed .. change the logic behind the key compression ..
